# Generated by Django 2.2.4 on 2019-08-30 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Extreme networks', max_length=35)),
                ('device_name', models.CharField(default='X450-G2', max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IP', models.GenericIPAddressField(protocol='IPv4', unique=True)),
                ('username', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=25)),
                ('ports_number', models.PositiveSmallIntegerField(default=0)),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='switches.Device')),
            ],
        ),
        migrations.CreateModel(
            name='Switch_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(default='extreme_exos', max_length=35, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vlan_name', models.CharField(max_length=35)),
                ('VID', models.PositiveSmallIntegerField(null=True)),
                ('switch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='switches.Switch')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25, unique=True)),
                ('password', models.CharField(max_length=25)),
                ('switches', models.ManyToManyField(to='switches.Switch')),
            ],
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vlan', models.CharField(default='No Vlan', max_length=35)),
                ('number', models.PositiveSmallIntegerField()),
                ('port_state', models.BooleanField()),
                ('link_state', models.BooleanField()),
                ('speed', models.PositiveSmallIntegerField(default=100)),
                ('duplex', models.CharField(max_length=10)),
                ('tag', models.BooleanField(default=0)),
                ('switch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='switches.Switch')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='switch_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='switches.Switch_type'),
        ),
    ]
